### ISSUE TITLE
update optimise code

### ISSUE THREAD

**Issue by LucaYoy** [LucaYoy/Many-quantum-bodies-using-quantum-computing#19]
- [x] change the initial set of gates in the brick wall from random to more systematic appoach

**Comment by LucaYoy** [comment]
@as2457 Does the random matrix which perturbs the identity when constructing the initial gates have to be unitary/real/complex ? I left it as a random unitary but im not sure if that's fine.

**Comment by LucaYoy** [comment]
@as2457 @NicholasSynesi 

 ### Note to self to remember to discuss it in meeting

- I changed the initialisation of gates from random to the more systematic approach discussed but it seems there is no much change in the optimisation
- I then added another condition to the optimisation that says: 'if precision := 1-|overlap| is not at least 0.2 then keep going until max number of sweeps is reached or until we finally break the plateau' I was hoping that this will hopefully break the **potential** plateau reached by letting the code run for more sweeps, in case that is the best it can do then max nr of sweeps will be reached and we break the code. Here im gauging that:  max nr sweep reached --> no plateau (best we can do); precision<0.2 ---> we like that and that's the most we care about so now just look at change in overlap between sweeps; 
- Now this **potential** plateau problem only occurs for N=8;M = 1,2 (low nr of layers)
- Doing the above for these cases brings an unexpected result. The code keeps running as it identified a **potential** plateau (as it should) however to my surprise instead of reaching max nr of sweeps, an exception is Brought up somewhere along the journey, the overlap decreased at some point in the sweep!
- Upon examining the numbers, it seems that the code keeps running and is stuck at the **potential** plateau (as it should) but then it seems that the overlap decreases, now I believe that is because we reached pythons numerical accuracy in the floats and crazy stuff happens after that.☠️
- With this analysis I believe that we should gauge this by simply saying that 'if the plateau is so stubborn that python goes crazy then lets just assume this is not a plateau and its the best we can do' 
- Not sure about last two points open for discussion 🤷🏻‍♂️

**Comment by AdamSmith-physics** [comment]
@LucaYoy The random matrix is not so important, it is just to get away from identity. Personally, I would set it as a general complex matrix sampled from a normal distribution. Making this Hermitian and then exponentiating ensures the final matrix will be unitary.

@LucaYoy @NicholasSynesi, instead of raising an error when the overlap decreases, you might have to change it to an decrease of more than say 10^(-12). I agree that this is probably just numerical precision from staying at the same point. 

You could also add a minimum number of steps. I think this will take quite a large number of iterations to converge properly. For some tests, you might want to remove all stopping criteria and just run all iterations to see what's happening. Analysis of the optimisation procedure could definitely end up being it's own chapter in your thesis.

**Comment by AdamSmith-physics** [comment]
Also note, if you save the gates to file, then you should be able to continue the optimisation process without restarting if necessary.

In our next meeting we can come up for a plan to properly investigate the optimisation.
